apiVersion: apps/v1
kind: Deployment
metadata:
  name: ''
  namespace: ''
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy: ''
  template:
    metadata:
      labels:
        deploy: ''
    spec:
      containers:
      - name: ''
        command: []
        args: []
        image: ''
        imagePullPolicy: Always
# Modify your container port, this port should be same with service port and target port
        ports:
        - containerPort: 5001
# Modify your requests and limits resource
        resources:
          requests:
            cpu: 100m
            memory: "100Mi"
          limits:
            cpu: 400m
            memory: "500Mi"
      imagePullSecrets:
        - name: harbor-login
