stages:
    - build
    - deploy
    - cloud

build_collector:
    stage: build
    script:
        - echo "Start docker build data collector stage....."
        - python cookbook/script/buildimg.py dataprovider
    tags:
        - docker-runner

deploy_collector_docker:
    stage: deploy
    script:
        - echo "Auto deploy to INX Cloud Platform...."
        - python cookbook/script/deployimg.py dataprovider
    tags:
        - docker-runner
    only:
        refs:
            - master

gen_service:
    stage: cloud
    script:
        - echo "Creating datacollectorapi-service"
        - python cookbook/script/gen-service.py
    tags:
        - docker-runner
    when: manual

gen_ingress:
    stage: cloud
    script:
        - echo "Creating ingress for iampweb, datacollector, dataprovider..."
        - python cookbook/script/gen-ingress.py
    tags:
        - docker-runner
    when: manual

gen_img_tar:
    stage: cloud
    script:
        - echo "Generate Prod Image Tar File...."
        - python cookbook/script/gen_prod_img_tar.py dataprovider
    tags:
        - docker-runner
    when: manual

