stages:
    - build
    - deploy

build_collector:
    stage: build
    script:
        - echo "Start docker build data collector stage....."
        - python cookbook/script/buildimg.py wslcollector
    tags:
        - docker-runner

deploy_collector_docker:
    stage: deploy
    script:
        - echo "Auto deploy to INX Cloud Platform...."
        - python cookbook/script/deployimg.py wslcollector
    tags:
        - docker-runner
    only:
        refs:
            - master

